### ISSUE TITLE
Support DNS failover

### ISSUE THREAD

**Issue by teddychan** [postmen/postmen-sdk-ruby#15]
It will be great if SDK support DNS fail over.

e.g.

if sandbox-api.postmen.`com` fail in DNS lookup, 
it can fall back to sandbox-api.postmen.`net`

**Comment by krzyzak** [comment]
oh, that's a good idea - didn't know that we actually have more than one domain there.
Could you prepare a list of domains (for both sandbox and production)?

**Comment by krzyzak** [comment]
Done
